const portfolioConfig = {
  "profileImage": "profile.webp",
  "work": {
    "1": {
      "title": "Hiding in Plain Sight",
      "year": "2023",
      "type": "Drama Short Film",
      "role": "Director, Cinematographer",
      "info": "",
      "link": "https://www.youtube.com/watch?v=7ntooo_Zoug",
      "thumbnail": "work/1/thumbnail.webp",
      "stills": [
        "work/1/stills/1.webp",
        "work/1/stills/2.webp",
        "work/1/stills/3.webp",
        "work/1/stills/4.webp",
        "work/1/stills/5.webp"
      ],
      "bts": [
        "work/1/bts/1.webp",
        "work/1/bts/2.webp",
        "work/1/bts/3.webp"
      ]
    },
    "2": {
      "title": "The Manor Episode 1",
      "year": "2023",
      "type": "Drama Web Series",
      "role": "Cinematographer",
      "info": "",
      "link": "",
      "thumbnail": "work/2/thumbnail.webp",
      "stills": [
        "work/2/stills/1.webp",
        "work/2/stills/2.webp",
        "work/2/stills/3.webp",
        "work/2/stills/4.webp",
        "work/2/stills/5.webp",
        "work/2/stills/6.webp",
        "work/2/stills/7.webp",
        "work/2/stills/8.webp",
        "work/2/stills/9.webp",
        "work/2/stills/10.webp",
        "work/2/stills/11.webp",
        "work/2/stills/12.webp"
      ],
      "bts": [
        "work/2/bts/1.webp",
        "work/2/bts/2.webp",
        "work/2/bts/3.webp",
        "work/2/bts/4.webp",
        "work/2/bts/5.webp",
        "work/2/bts/6.webp",
        "work/2/bts/7.webp",
        "work/2/bts/8.webp",
        "work/2/bts/9.webp"
      ]
    },
    "3": {
      "title": "Tidal Bonds",
      "year": "2023",
      "type": "Drama Short Film",
      "role": "Writer, Director",
      "info": "Bronze award - 2023 Aquarium of the Pacific Film Festival",
      "link": "https://www.youtube.com/watch?v=BV-6J14Aqsw",
      "thumbnail": "work/3/thumbnail.webp",
      "stills": [
        "work/3/stills/1.webp",
        "work/3/stills/2.webp",
        "work/3/stills/3.webp",
        "work/3/stills/4.webp",
        "work/3/stills/5.webp"
      ],
      "bts": []
    },
    "4": {
      "title": "VEX Robotics Over Under Regional Reveal",
      "year": "2024",
      "type": "Promotional",
      "role": "Director, Cinematographer",
      "info": "",
      "link": "https://www.youtube.com/watch?v=VV8Yw-59PoQ",
      "thumbnail": "work/4/thumbnail.webp",
      "stills": [
        "work/4/stills/1.webp",
        "work/4/stills/2.webp",
        "work/4/stills/3.webp",
        "work/4/stills/4.webp",
        "work/4/stills/5.webp",
        "work/4/stills/6.webp",
        "work/4/stills/7.webp",
        "work/4/stills/8.webp",
        "work/4/stills/9.webp",
        "work/4/stills/10.webp"
      ],
      "bts": [
        "work/4/bts/1.webp",
        "work/4/bts/2.webp",
        "work/4/bts/3.webp",
        "work/4/bts/4.webp",
        "work/4/bts/5.webp"
      ]
    },
    "5": {
      "title": "VEX Robotics High Stakes Early Season Reveal",
      "year": "2024",
      "type": "Promotional",
      "role": "Director, Cinematographer",
      "info": "",
      "link": "https://www.youtube.com/watch?v=ZU6qM1QNLcs",
      "thumbnail": "work/5/thumbnail.webp",
      "stills": [
        "work/5/stills/1.webp",
        "work/5/stills/2.webp",
        "work/5/stills/3.webp",
        "work/5/stills/4.webp",
        "work/5/stills/5.webp",
        "work/5/stills/6.webp",
        "work/5/stills/7.webp",
        "work/5/stills/8.webp",
        "work/5/stills/9.webp",
        "work/5/stills/10.webp",
        "work/5/stills/11.webp",
        "work/5/stills/12.webp"
      ],
      "bts": [
        "work/5/bts/1.webp",
        "work/5/bts/2.webp",
        "work/5/bts/3.webp",
        "work/5/bts/4.webp",
        "work/5/bts/5.webp",
        "work/5/bts/6.webp",
        "work/5/bts/7.webp",
        "work/5/bts/8.webp",
        "work/5/bts/9.webp",
        "work/5/bts/10.webp",
        "work/5/bts/11.webp",
        "work/5/bts/12.webp",
        "work/5/bts/13.webp"
      ]
    },
    "6": {
      "title": "Digital Postcards",
      "year": "2024-2025",
      "type": "Experimental",
      "role": "Director, Cinematographer",
      "info": "",
      "link": "",
      "thumbnail": "work/6/thumbnail.webp",
      "stills": [
        "work/6/stills/1.webp",
        "work/6/stills/2.webp",
        "work/6/stills/3.webp",
        "work/6/stills/4.webp",
        "work/6/stills/5.webp",
        "work/6/stills/6.webp",
        "work/6/stills/7.webp",
        "work/6/stills/8.webp",
        "work/6/stills/9.webp",
        "work/6/stills/10.webp",
        "work/6/stills/11.webp",
        "work/6/stills/12.webp",
        "work/6/stills/13.webp",
        "work/6/stills/14.webp",
        "work/6/stills/15.webp",
        "work/6/stills/16.webp"
      ],
      "bts": []
    },
    "7": {
      "title": "Silence is my Voice",
      "year": "2024",
      "type": "Drama Short Film",
      "role": "Cinematographer",
      "info": "",
      "link": "",
      "thumbnail": "work/7/thumbnail.webp",
      "stills": [
        "work/7/stills/1.webp",
        "work/7/stills/2.webp",
        "work/7/stills/3.webp",
        "work/7/stills/4.webp",
        "work/7/stills/5.webp",
        "work/7/stills/6.webp",
        "work/7/stills/7.webp",
        "work/7/stills/8.webp",
        "work/7/stills/9.webp",
        "work/7/stills/10.webp",
        "work/7/stills/11.webp"
      ],
      "bts": []
    },
    "8": {
      "title": "Waiting Room",
      "year": "2024",
      "type": "Drama Short Film",
      "role": "Cinematographer",
      "info": "Orange County School of the Arts - Best Picture 2024",
      "link": "",
      "thumbnail": "work/8/thumbnail.webp",
      "stills": [
        "work/8/stills/1.webp",
        "work/8/stills/2.webp",
        "work/8/stills/3.webp",
        "work/8/stills/4.webp",
        "work/8/stills/5.webp",
        "work/8/stills/6.webp",
        "work/8/stills/7.webp",
        "work/8/stills/8.webp",
        "work/8/stills/9.webp",
        "work/8/stills/10.webp",
        "work/8/stills/11.webp"
      ],
      "bts": [
        "work/8/bts/1.webp",
        "work/8/bts/2.webp",
        "work/8/bts/3.webp",
        "work/8/bts/4.webp",
        "work/8/bts/5.webp",
        "work/8/bts/6.webp",
        "work/8/bts/7.webp",
        "work/8/bts/8.webp",
        "work/8/bts/9.webp",
        "work/8/bts/10.webp",
        "work/8/bts/11.webp",
        "work/8/bts/12.webp"
      ]
    },
    "9": {
      "title": "My Roommate is a Filmmaker",
      "year": "2023",
      "type": "Comedy Short Film",
      "role": "Writer, Director",
      "info": "",
      "link": "https://www.youtube.com/watch?v=aZaXEEB_rls",
      "thumbnail": "work/9/thumbnail.webp",
      "stills": [
        "work/9/stills/1.webp",
        "work/9/stills/2.webp",
        "work/9/stills/3.webp",
        "work/9/stills/4.webp",
        "work/9/stills/5.webp",
        "work/9/stills/6.webp",
        "work/9/stills/7.webp",
        "work/9/stills/8.webp"
      ],
      "bts": [
        "work/9/bts/1.webp",
        "work/9/bts/2.webp",
        "work/9/bts/3.webp",
        "work/9/bts/4.webp",
        "work/9/bts/5.webp",
        "work/9/bts/6.webp",
        "work/9/bts/7.webp",
        "work/9/bts/8.webp",
        "work/9/bts/9.webp",
        "work/9/bts/10.webp",
        "work/9/bts/11.webp",
        "work/9/bts/12.webp"
      ]
    },
    "10": {
      "title": "VEX Robotics High Stakes February Reveal",
      "year": "2025",
      "type": "Promotional",
      "role": "Director, Cinematographer",
      "info": "",
      "link": "https://www.youtube.com/watch?v=_P9p1S8SMig&pp=ygUFMjkyMmM%3D",
      "thumbnail": "work/10/thumbnail.webp",
      "stills": [
        "work/10/stills/1.webp",
        "work/10/stills/2.webp",
        "work/10/stills/3.webp",
        "work/10/stills/4.webp",
        "work/10/stills/5.webp",
        "work/10/stills/6.webp"
      ],
      "bts": [
        "work/10/bts/1.webp",
        "work/10/bts/2.webp",
        "work/10/bts/3.webp",
        "work/10/bts/4.webp",
        "work/10/bts/5.webp",
        "work/10/bts/6.webp",
        "work/10/bts/7.webp",
        "work/10/bts/8.webp",
        "work/10/bts/9.webp"
      ]
    },
    "11": {
      "title": "VEX Robotics High Stakes Regional Reveal",
      "year": "2025",
      "type": "Promotional",
      "role": "Director, Cinematographer",
      "info": "",
      "link": "https://www.youtube.com/watch?v=FYPiEvNyMY4&pp=ygUFMjkyMmM%3D",
      "thumbnail": "work/11/thumbnail.webp",
      "stills": [
        "work/11/stills/1.webp",
        "work/11/stills/2.webp",
        "work/11/stills/3.webp",
        "work/11/stills/4.webp",
        "work/11/stills/5.webp",
        "work/11/stills/6.webp",
        "work/11/stills/7.webp",
        "work/11/stills/8.webp",
        "work/11/stills/9.webp",
        "work/11/stills/10.webp",
        "work/11/stills/11.webp",
        "work/11/stills/12.webp",
        "work/11/stills/13.webp"
      ],
      "bts": []
    },
    "12": {
      "title": "Open",
      "year": "2025",
      "type": "Drama Short Film",
      "role": "Cinematographer, Editor",
      "info": "",
      "link": "",
      "thumbnail": "work/12/thumbnail.webp",
      "stills": [
        "work/12/stills/1.webp",
        "work/12/stills/2.webp",
        "work/12/stills/3.webp",
        "work/12/stills/4.webp",
        "work/12/stills/5.webp",
        "work/12/stills/6.webp",
        "work/12/stills/7.webp",
        "work/12/stills/8.webp",
        "work/12/stills/9.webp",
        "work/12/stills/10.webp",
        "work/12/stills/11.webp",
        "work/12/stills/12.webp"
      ],
      "bts": [
        "work/12/bts/1.webp",
        "work/12/bts/2.webp",
        "work/12/bts/3.webp",
        "work/12/bts/4.webp",
        "work/12/bts/5.webp",
        "work/12/bts/6.webp",
        "work/12/bts/7.webp"
      ]
    },
    "13": {
      "title": "48hr Film Fest Promo",
      "year": "2025",
      "type": "Promotional",
      "role": "Director, Cinematographer",
      "info": "Main promotional video for Orange County 48 hour film festival",
      "link": "https://www.instagram.com/reel/DJAdSz0TH1z/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==",
      "thumbnail": "work/13/thumbnail.webp",
      "stills": [
        "work/13/stills/1.webp",
        "work/13/stills/2.webp",
        "work/13/stills/3.webp",
        "work/13/stills/4.webp",
        "work/13/stills/5.webp",
        "work/13/stills/6.webp",
        "work/13/stills/7.webp",
        "work/13/stills/8.webp",
        "work/13/stills/9.webp",
        "work/13/stills/10.webp"
      ],
      "bts": []
    },
    "14": {
      "title": "Orange County 48hr",
      "year": "2025",
      "type": "Film Festival",
      "role": "Producer, Director",
      "info": "Orange County 48 Hour Film Festival students create a film from start to finish in 48 hrs with a common theme. We had 18 total submission with 80 participants among 11 different Orange County high schools.",
      "link": "https://www.instagram.com/oc.48hr.filmfest/",
      "thumbnail": "work/14/thumbnail.webp",
      "stills": [],
      "bts": [
        "work/14/bts/1.webp",
        "work/14/bts/2.webp",
        "work/14/bts/3.webp",
        "work/14/bts/4.webp",
        "work/14/bts/5.webp",
        "work/14/bts/6.webp",
        "work/14/bts/7.webp",
        "work/14/bts/8.webp",
        "work/14/bts/9.webp",
        "work/14/bts/10.webp",
        "work/14/bts/11.webp",
        "work/14/bts/12.webp",
        "work/14/bts/13.webp",
        "work/14/bts/14.webp",
        "work/14/bts/15.webp",
        "work/14/bts/16.webp",
        "work/14/bts/17.webp"
      ]
    },
    "15": {
      "title": "before we leave",
      "year": "2025",
      "type": "Experimental",
      "role": "Cinematographer, Editor",
      "info": "",
      "link": "https://www.instagram.com/p/DPaMci4DHZ5/",
      "thumbnail": "work/15/thumbnail.webp",
      "stills": [
        "work/15/stills/1.webp",
        "work/15/stills/2.webp",
        "work/15/stills/3.webp",
        "work/15/stills/4.webp",
        "work/15/stills/5.webp",
        "work/15/stills/6.webp",
        "work/15/stills/7.webp",
        "work/15/stills/8.webp",
        "work/15/stills/9.webp"
      ],
      "bts": []
    },
    "16": {
      "title": "Power Play",
      "year": "2025",
      "type": "Drama Short Film",
      "role": "Co-Director, Cinematographer",
      "info": "Orange County School of the Arts - 2025 Best Cinemtography, Best Sound Design, Best Editing<br>All American Film Festival - 2025 Best Cinematography Nominee",
      "link": "https://www.instagram.com/power.play.hockey.film/",
      "thumbnail": "work/16/thumbnail.webp",
      "stills": [
        "work/16/stills/1.webp",
        "work/16/stills/2.webp",
        "work/16/stills/3.webp",
        "work/16/stills/4.webp",
        "work/16/stills/5.webp",
        "work/16/stills/6.webp",
        "work/16/stills/7.webp",
        "work/16/stills/8.webp",
        "work/16/stills/9.webp",
        "work/16/stills/10.webp",
        "work/16/stills/11.webp",
        "work/16/stills/12.webp",
        "work/16/stills/13.webp",
        "work/16/stills/14.webp",
        "work/16/stills/15.webp",
        "work/16/stills/16.webp",
        "work/16/stills/17.webp",
        "work/16/stills/18.webp",
        "work/16/stills/19.webp"
      ],
      "bts": [
        "work/16/bts/1.webp",
        "work/16/bts/2.webp",
        "work/16/bts/3.webp",
        "work/16/bts/4.webp",
        "work/16/bts/5.webp",
        "work/16/bts/6.webp",
        "work/16/bts/7.webp",
        "work/16/bts/8.webp",
        "work/16/bts/9.webp",
        "work/16/bts/10.webp",
        "work/16/bts/11.webp",
        "work/16/bts/12.webp",
        "work/16/bts/13.webp",
        "work/16/bts/14.webp",
        "work/16/bts/15.webp",
        "work/16/bts/16.webp",
        "work/16/bts/17.webp",
        "work/16/bts/18.webp",
        "work/16/bts/19.webp",
        "work/16/bts/20.webp",
        "work/16/bts/21.webp",
        "work/16/bts/22.webp",
        "work/16/bts/23.webp",
        "work/16/bts/24.webp",
        "work/16/bts/25.webp",
        "work/16/bts/26.webp",
        "work/16/bts/27.webp",
        "work/16/bts/28.webp",
        "work/16/bts/29.webp",
        "work/16/bts/30.webp",
        "work/16/bts/31.webp",
        "work/16/bts/32.webp",
        "work/16/bts/33.webp",
        "work/16/bts/34.webp",
        "work/16/bts/35.webp",
        "work/16/bts/36.webp",
        "work/16/bts/37.webp",
        "work/16/bts/38.webp",
        "work/16/bts/39.webp",
        "work/16/bts/40.webp",
        "work/16/bts/41.webp",
        "work/16/bts/42.webp",
        "work/16/bts/43.webp",
        "work/16/bts/44.webp",
        "work/16/bts/45.webp",
        "work/16/bts/46.webp"
      ]
    },
    "17": {
      "title": "Inertia",
      "year": "2026",
      "type": "Drama Short Film",
      "role": "Cinematographer",
      "info": "",
      "link": "https://www.instagram.com/inertiashortfilm/",
      "thumbnail": "work/17/thumbnail.webp",
      "stills": [
        "work/17/stills/1.webp",
        "work/17/stills/2.webp",
        "work/17/stills/3.webp",
        "work/17/stills/4.webp",
        "work/17/stills/5.webp",
        "work/17/stills/6.webp",
        "work/17/stills/7.webp",
        "work/17/stills/8.webp",
        "work/17/stills/9.webp",
        "work/17/stills/10.webp",
        "work/17/stills/11.webp",
        "work/17/stills/12.webp"
      ],
      "bts": [
        "work/17/bts/1.webp",
        "work/17/bts/2.webp",
        "work/17/bts/3.webp",
        "work/17/bts/4.webp",
        "work/17/bts/5.webp",
        "work/17/bts/6.webp",
        "work/17/bts/7.webp",
        "work/17/bts/8.webp",
        "work/17/bts/9.webp",
        "work/17/bts/10.webp"
      ]
    },
    "18": {
      "title": "Zebra斑马",
      "year": "2026",
      "type": "Drama Short Film",
      "role": "Cinematographer",
      "info": "",
      "link": "https://www.instagram.com/zebraa_film/",
      "thumbnail": "work/18/thumbnail.webp",
      "stills": [
        "work/18/stills/1.webp",
        "work/18/stills/2.webp",
        "work/18/stills/3.webp",
        "work/18/stills/4.webp",
        "work/18/stills/5.webp",
        "work/18/stills/6.webp",
        "work/18/stills/7.webp",
        "work/18/stills/8.webp",
        "work/18/stills/9.webp",
        "work/18/stills/10.webp",
        "work/18/stills/11.webp",
        "work/18/stills/12.webp",
        "work/18/stills/13.webp",
        "work/18/stills/14.webp"
      ],
      "bts": [
        "work/18/bts/1.webp",
        "work/18/bts/2.webp",
        "work/18/bts/3.webp",
        "work/18/bts/4.webp",
        "work/18/bts/5.webp",
        "work/18/bts/6.webp",
        "work/18/bts/7.webp",
        "work/18/bts/8.webp",
        "work/18/bts/9.webp",
        "work/18/bts/10.webp",
        "work/18/bts/11.webp",
        "work/18/bts/12.webp",
        "work/18/bts/13.webp",
        "work/18/bts/14.webp",
        "work/18/bts/15.webp",
        "work/18/bts/16.webp",
        "work/18/bts/17.webp",
        "work/18/bts/18.webp"
      ]
    }
  },
  "photography": [
    "photography/1.webp",
    "photography/2.webp",
    "photography/3.webp",
    "photography/4.webp",
    "photography/5.webp",
    "photography/6.webp",
    "photography/7.webp",
    "photography/8.webp",
    "photography/9.webp",
    "photography/10.webp",
    "photography/11.webp",
    "photography/12.webp",
    "photography/13.webp",
    "photography/14.webp",
    "photography/15.webp",
    "photography/16.webp",
    "photography/17.webp",
    "photography/18.webp",
    "photography/19.webp",
    "photography/20.webp",
    "photography/21.webp"
  ],
  "graphic": [
    "graphic-design/1.webp",
    "graphic-design/2.webp",
    "graphic-design/3.webp",
    "graphic-design/4.webp",
    "graphic-design/5.webp",
    // "graphic-design/6.webp",
    "graphic-design/7.webp",
    "graphic-design/8.webp",
    // "graphic-design/9.webp",
    "graphic-design/10.webp",
    //"graphic-design/11.webp",
    "graphic-design/12.webp",
    "graphic-design/13.webp",
    "graphic-design/14.webp",
    "graphic-design/15.webp",
    "graphic-design/16.webp",
    "graphic-design/17.webp",
    "graphic-design/18.webp",
    "graphic-design/19.webp",
    "graphic-design/20.webp",
    "graphic-design/21.webp"
  ],
  "crew": [
    "crew/1.webp",
    "crew/2.webp",
    "crew/3.webp",
    "crew/4.webp",
    "crew/5.webp",
    "crew/6.webp",
    "crew/7.webp",
    "crew/8.webp",
    "crew/9.webp",
    "crew/10.webp",
    "crew/11.webp",
    "crew/12.webp",
    "crew/13.webp",
    "crew/14.webp",
    "crew/15.webp",
    "crew/16.webp",
    "crew/17.webp",
    "crew/18.webp",
    "crew/19.webp",
    "crew/20.webp",
    "crew/21.webp",
    "crew/22.webp",
    "crew/23.webp",
    "crew/24.webp",
    "crew/25.webp",
    "crew/26.webp"
  ]
};
